import JAVA_TYPE from "./JavaType";

const ARCHITECTURE_LEVEL = {
    lv1: [JAVA_TYPE.JAVA_ROOT_NODE],
    lv2: [JAVA_TYPE.JAVA_PACKAGE_NODE],
    lv3: [
        JAVA_TYPE.JAVA_CLASS_NODE,
        JAVA_TYPE.JAVA_INTERFACE_NODE,
        JAVA_TYPE.JAVA_ENUM_NODE,
        JAVA_TYPE.JAVA_INITIALIZER_NODE,
    ],
    lv4: [
        JAVA_TYPE.JAVA_METHOD_NODE,
        JAVA_TYPE.JAVA_FIELD_NODE,
    ]
}

export default ARCHITECTURE_LEVEL;